カラオケ企画ページの作成
YNUFes-tech/ynufes-tokiwa22 pull request #4
Opened 2022-09-26 11:42 UTC by sssaaaeee

2022-09-26 11:50 UTC, shion1305 commented
コンフリクトの解消はこちらで済ませておきます!

2022-09-26 11:55 UTC, shion1305 commented
すごい..!クォリティー高くてびっくりしました

2022-09-26 11:59 UTC, shion1305 requested changes
画面の横幅が340px以下の時に画像が画面外にはみ出して
レイアウトが崩れてしまっているので
そこの調整をお願いしたいです..!
それが完了したいマージしましょう!

2022-09-26 12:01 UTC, shion1305 commented
画面の横幅が320px(できれば300px)以上で表示が正しくなれれば大丈夫かなと思います!

2022-09-26 12:09 UTC, shion1305 commented
メディアクエリを使えばうまく解決できるかと思います!
(連投ごめんなさい....)

こことかも使っているので参考までに
https://github.com/YNUFes-tech/ynufes-tokiwa22/blob/3f8e22b0992a2e0c3668f6da8a7b0d3bfb3ab530/src/views/EventListView.vue#L197-L225

2022-09-27 01:23 UTC, sssaaaeee commented
了解です！

2022-09-28 12:25 UTC, shion1305 approved these changes
LGTM!
お疲れ様です!

2022-10-04 05:27 UTC, sobu138 approved these changes

2022-10-04 05:28 UTC, merged